languageCode = "en-us"
theme = "kiss"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

title = "Ann Arbor R User Group"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Author"
    description = "A website built through Hugo and blogdown."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "a2rug"
    twitter = "annarborrusers"
    meetup = "Ann-Arbor-R-User-Group"
    email = "AnnArborRUserGroup@gmail.com"

[menu]

    [[menu.main]]
        name = "About"
        identifier = "about"
        weight = 300
        url = "/about/"

    [[menu.main]]
        name = "Posts"
        identifier = "posts"
        weight = 100
        url = "/post/"
