languageCode = "en-us"
theme = "hyde-hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Author"
    title = "Ann Arbor R User Group"
    description = "A website built through Hugo and blogdown."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "a2rug"
    twitter = "annarborrusers"
    meetup = "https://www.meetup.com/Ann-Arbor-R-User-Group/"  # doesn't work
    email = "AnnArborRUserGroup@gmail.com"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
